name: file_manager
description: FileManager is a wonderful widget that allows you to manage files
  and folders, pick files and folders, and do a lot more. Designed to feel like
  part of the Flutter framework.
publish_to: none
version: 1.0.2
homepage: https://github.com/DevsOnFlutter
repository: https://github.com/DevsOnFlutter/file_manager
documentation: https://github.com/DevsOnFlutter/file_manager/blob/main/README.md

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
    git: https://github.com/kumsumit/path_provider.git

dev_dependencies:
  flutter_test:
    sdk: flutter
